platform :ios, '9.0'
require_relative  '../../rn-pod'

target 'ZXTTRNTest' do
  # Pods for ZXTTRNTest
  
#   pod 'LookinServer', :configurations => ['Debug']
  pod 'LookinServer'
  pod 'ZXTTInRN', :path =>  '../../iOS'
  use_rn_pod!('../..')

  target 'ZXTTRNTestTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end

target 'ZXTTRNTest-tvOS' do
  # Pods for ZXTTRNTest-tvOS

  target 'ZXTTRNTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
