platform :ios, '9.0'
require_relative  './node_modules/zxtt-rn/rn-pod'

target 'ZXTTRNTest' do
  # Pods for ZXTTRNTest
  pod 'ZXTTInRN', :path =>  './node_modules/zxtt-rn/iOS'
  use_rn_pod!

  target 'ZXTTRNTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'ZXTTRNTest-tvOS' do
  # Pods for ZXTTRNTest-tvOS

  target 'ZXTTRNTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
